# Generated by Django 5.2.17 on 2026-08-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("jobs", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["student", "status"], name="jobs_applic_student_09cda8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["job", "status"], name="jobs_applic_job_id_a25382_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["job", "-applied_at"], name="jobs_applic_job_id_020f92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["company", "status", "-created_at"],
                name="jobs_job_company_d49781_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_active", "status", "-created_at"],
                name="jobs_job_is_acti_415c62_idx",
            ),
        ),
    ]
