# Generated by Django 5.1 on 2026-08-20 08:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enrollment_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("branch", models.CharField(blank=True, db_index=True, max_length=100)),
                ("course", models.CharField(blank=True, max_length=50)),
                ("semester", models.IntegerField(default=1)),
                (
                    "cgpa",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=15)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("ats_score", models.IntegerField(default=0)),
                ("ai_feedback", models.TextField(blank=True)),
                ("streak_count", models.IntegerField(default=0)),
                ("total_points", models.IntegerField(default=0)),
                ("last_active_date", models.DateField(auto_now=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.collegeprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("tech_stack", models.JSONField(blank=True, default=list)),
                ("project_url", models.CharField(blank=True, max_length=500)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="students.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("issuer", models.CharField(blank=True, max_length=200)),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("certificate_url", models.CharField(blank=True, max_length=500)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="students.studentprofile",
                    ),
                ),
            ],
        ),
    ]
