# Generated by Django 5.2.17 on 2026-08-26 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["college", "branch"], name="students_st_college_f872ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["-total_points"], name="students_st_total_p_7a5fe9_idx"
            ),
        ),
    ]
