# Generated by Django 5.2.17 on 2026-08-26 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["user", "status"], name="analytics_s_user_id_837b22_idx"
            ),
        ),
    ]
