# Generated by Django 5.2.17 on 2026-08-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interviews", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["application", "status"], name="interviews__applica_96ea9d_idx"
            ),
        ),
    ]
