# Generated by Django 5.1 on 2026-08-20 08:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("joining_date", models.CharField(blank=True, max_length=50)),
                ("hash_sha256", models.CharField(max_length=64)),
                (
                    "previous_hash",
                    models.CharField(
                        default="0000000000000000000000000000000000000000000000000000000000000000",
                        max_length=64,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("verified_count", models.IntegerField(default=0)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_letter",
                        to="jobs.application",
                    ),
                ),
            ],
        ),
    ]
